version: '3.1'
services:
  postgres:
    image: postgres:13-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: django
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "django", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8082:8081
    depends_on:
      - postgres
  django:
    image: almightydreamer/lab34:latest
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:admin@postgres/django
    ports:
      - 8000:8000
    depends_on:
      - postgres
  migrations:
    build: .
    image: almightydreamer/lab34:latest
    command: python manage.py migrate
    environment:
      DATABASE_URL: postgresql://postgres:admin@postgres/django
    depends_on:
      - postgres
  users:
    build: .
    image: almightydreamer/lab34:latest
    command: python manage.py createsuperuser --noinput
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DATABASE_URL: postgresql://postgres:admin@postgres/django
    depends_on:
      - postgres
      - migrations

